// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSvocmYd8o2Bk3h4MNPzMrH-yM-cCf1Q',
    appId: '1:827237908922:web:a60334dce3ba572ad81d83',
    messagingSenderId: '827237908922',
    projectId: 'streamdotfinance',
    authDomain: 'streamdotfinance.firebaseapp.com',
    storageBucket: 'streamdotfinance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6fotfF7xRQnrkPkH8nlO7fXVlWJPe1Y',
    appId: '1:827237908922:android:8e427ad2259e6ce5d81d83',
    messagingSenderId: '827237908922',
    projectId: 'streamdotfinance',
    storageBucket: 'streamdotfinance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Mqw2-96KiFxHoS5ml7rUQ3lUOsYH2kg',
    appId: '1:827237908922:ios:42a3e1a6adb66662d81d83',
    messagingSenderId: '827237908922',
    projectId: 'streamdotfinance',
    storageBucket: 'streamdotfinance.firebasestorage.app',
    iosBundleId: 'com.zappy.streamdot',
  );
}
